name: running_trainer
description: A fitness app.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^0.1.2
  shared_preferences: ^0.5.3+4
  geolocator: ^5.1.4+2
  numberpicker: ^1.1.0
  google_maps_flutter: ^0.5.21+8
  latlong: ^0.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.3


flutter:
  fonts:
    - family: SUNDAY
      fonts:
        - asset: assets/fonts/SUNDAY.ttf
  assets:
    - assets/running.gif
  uses-material-design: true